name: Cypress tests

on:
  pull_request:
    branches:
    - master

jobs:
  cypress:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [13.x, 12.x, 10.x]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run css:build
        npm test
      env:
        CI: true
        SESSION_SECRET: ${{secrets.SESSION_SECRET}}
